### ISSUE TITLE
Include a less strict version of the parser

### ISSUE THREAD

**Issue by nicovn** [aiderpmsi/libHprim#1]
The current version of the parser is extremely strict ... while in practice there are a lot of messages that don't correspond 100% to the HPRIM standard ... e.g. which add a non existing repetition, or don't fill in a required field.

Example message:

H|~^&|88||TEST~TEST||ADM|||HPRIM||P|H2.1~R|20130122113948
P|1|703601||614268038|INCONNU~INCONNU~~~Mle~||19890625|F||RUE 4~~TEST~~59960~||00.00.00.00.00|||||||||~~~~||20130122113900|IP|~~1531~1531~35~1~5~||||1|||||
L|1||1|3

It would be nice to have a less strict version of the parser (e.g. like the HL7 to XML conversion in Mirth Connect) that does not take into account required fields/additional components/fields when generating the XML message.

**Comment by aiderpmsi** [comment]
I'm planning a 'crapy' parser for version 3.3.0. The version in the git iss already working for your message (except that the header should be H|~^\&|, but github removes \).

It will enable parsing of mostly anything that looks like HPRIM.

But it's always better to point the fact that a lot of vendors who claim they support HPRIM are doing it very badly. They don't even conform to the syntax defined by InteropSanté (and I won't say anything about the content of the files even syntaxically correct).

For your message, strict HPRIM is :
H|~^\&|88||TEST~TEST||ADM|||002~DESTINATION||P|H2.1~R|20130122113948
P|1|703601||614268038|INCONNU~INCONNU~~~Mle~||19890625|F||RUE 4~~TEST~~59960~||00.00.00.00.00|||||||||||20130122113900|IP|~~1531~1531~35~1~5~||||1|||||
L|1||1|3

**Comment by aiderpmsi** [comment]
Version 3.4.0 has now :

1 - Strict parser (hprim) with 3 levels of conformance
2 - Dirty (nicer name than crapy) parser which can parse almost anything

I think the issue can be closed.

**Comment by nicovn** [comment]
Thanks a lot for the modifications !

I'll test it today ...
